#!/usr/bin/env bash

export VIM_PROJNAME="teahaz"
export VIM_PROJCONF="$BASH_SOURCE"
export VIM_PROJPATH="$(realpath `dirname $VIM_PROJCONF`)"
# export VIM_COMMAND="python3 $VIM_PROJPATH/tests/container_test.py"
export VIM_NOTES="$VIM_PROJPATH/notes.md"

echo "Set up project \"$VIM_PROJNAME\" at path \"$VIM_PROJPATH\"."
